/*
 * Copyright 2020 Wultra s.r.o.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.wultra.security.pqc.sike;

import com.wultra.security.pqc.sike.crypto.KeyGenerator;
import com.wultra.security.pqc.sike.crypto.Sidh;
import com.wultra.security.pqc.sike.math.api.Fp2Element;
import com.wultra.security.pqc.sike.model.ImplementationType;
import com.wultra.security.pqc.sike.model.Party;
import com.wultra.security.pqc.sike.param.SikeParam;
import com.wultra.security.pqc.sike.param.SikeParamP434;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.junit.jupiter.api.Test;

import java.security.GeneralSecurityException;
import java.security.KeyPair;
import java.security.Security;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Test of SIDH key exchange.
 *
 * @author Roman Strobl, roman.strobl@wultra.com
 */
public class SidhTest {

    static {
        Security.addProvider(new BouncyCastleProvider());
    }

    @Test
    public void testSidh() throws GeneralSecurityException {
        SikeParam sikeParam = new SikeParamP434(ImplementationType.OPTIMIZED);
        System.out.println("Prime: " + sikeParam.getPrime());
        KeyGenerator keyGenerator = new KeyGenerator(sikeParam);
        Sidh sidh = new Sidh(sikeParam);
        int loopCount = 10;
        long timeTotalA = 0L;
        long timeTotalB = 0L;
        for (int i = 0; i < loopCount; i++) {
            System.out.println("----------------------------------------");
            long timeStartA = System.currentTimeMillis();
            KeyPair keyPairA = keyGenerator.generateKeyPair(Party.ALICE);
            System.out.println("Alice's keypair:");
            System.out.println("Private key: " + keyPairA.getPrivate());
            System.out.println("Public key: " + keyPairA.getPublic());
            long timeEndA = System.currentTimeMillis();
            timeTotalA += (timeEndA - timeStartA);

            long timeStartB = System.currentTimeMillis();
            KeyPair keyPairB = keyGenerator.generateKeyPair(Party.BOB);
            System.out.println("Bob's keypair:");
            System.out.println("Private key: " + keyPairB.getPrivate());
            System.out.println("Public key: " + keyPairB.getPublic());
            long timeEndB = System.currentTimeMillis();
            timeTotalB += (timeEndB - timeStartB);

            // Bob's public key is sent to Alice
            timeStartA = System.currentTimeMillis();
            Fp2Element secretA = sidh.generateSharedSecret(Party.ALICE, keyPairA.getPrivate(), keyPairB.getPublic());
            System.out.println("Shared secret generated by Alice: " + secretA);
            timeEndA = System.currentTimeMillis();
            timeTotalA += (timeEndA - timeStartA);

            // Alice's public key is sent to Bob
            timeStartB = System.currentTimeMillis();
            Fp2Element secretB = sidh.generateSharedSecret(Party.BOB, keyPairB.getPrivate(), keyPairA.getPublic());
            System.out.println("Shared secret generated by Bob:   " + secretB);
            timeEndB = System.currentTimeMillis();
            timeTotalB += (timeEndB - timeStartB);

            boolean match = secretA.equals(secretB);
            System.out.println("Secrets match: " + match);
            assertTrue(match, "Secrets do not match");
        }
        System.out.println("Average execution time (Alice): " + ((double)timeTotalA / loopCount) + " ms");
        System.out.println("Average execution time (Bob): " + ((double)timeTotalB / loopCount) + " ms");
    }
}
