/*
 * Copyright 2020 Wultra s.r.o.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.wultra.security.pqc.sike.crypto;

import com.wultra.security.pqc.sike.param.SikeParam;

import java.math.BigInteger;
import java.security.SecureRandom;

/**
 * Random generator for key material.
 *
 * @author Roman Strobl, roman.strobl@wultra.com
 */
public class RandomGenerator {

    // TODO - consider using Secure Random from Bouncy Castle
    private final SecureRandom secureRandom = new SecureRandom();

    /**
     * Generate a random key.
     * @param sikeParam SIKE parameters.
     * @return Random BigInteger usable as a private key.
     */
    public BigInteger generateRandomKey(SikeParam sikeParam) {
        BigInteger prime = sikeParam.getPrime();
        return new BigInteger(prime.bitLength(), secureRandom);
    }

    /**
     * Generate random bytes.
     * @param length Length of generated byte array.
     * @return Byte array with random bytes.
     */
    public byte[] generateRandomBytes(int length) {
        byte[] randomBytes = new byte[length];
        secureRandom.nextBytes(randomBytes);
        return randomBytes;
    }

}
